### ISSUE TITLE
Running with JBPM

### ISSUE THREAD

**Issue by mohsinkhalid122** [ThinkBigAnalytics/AoaDockerComposeDemos#14]
The docker compose command mentioned in the Running with JBPM section in the ReadMe has typos in the yaml file extensions, .yml should be .yaml 
the commad is : docker-compose -f docker-compose.yml -f docker-compose.jbpm.yml up
should be : docker-compose -f docker-compose.yaml -f docker-compose.jbpm.yaml up

**Comment by nunomachado** [comment]
Fixed in #16
