### ISSUE TITLE
Configure Gogs Urls

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaDockerComposeDemos#2]
Make Gogs repository urls copy and pastable via the UI - currently it shows defaults which aren't correct and make the demo harder to use for e.g. showing how to add a new project

https://gogs.io/docs/installation/configuration_and_run.html

@dominik-koch-tb @albertofont @orionrk  fyi

**Comment by Christian-TD** [comment]
fyi @willfleury obsolete and stale, closing issue
