### ISSUE TITLE
Error while deploying model in Airflow

### ISSUE THREAD

**Issue by mohsinkhalid122** [ThinkBigAnalytics/AoaDockerComposeDemos#26]
I'm facing this error while deploying the model onto Airflow. In AOps the model is deployed sucessfully but in Airflow I get this error:
**Broken DAG: [/usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py] No module named 'kubernetes' **

On the command line looks like python kubernetes library issue, the error is as follows:

**airflow      | [2020-12-14 09:58:37,805] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py
airflow      | Traceback (most recent call last):
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
airflow      |     m = imp.load_source(mod_name, filepath)
airflow      |   File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
airflow      |     module = _load(spec)
airflow      |   File "<frozen importlib._bootstrap>", line 696, in _load
airflow      |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
airflow      |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
airflow      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
airflow      |   File "/usr/local/airflow/dags/61fa8e00-f14a-4dfb-ae13-9d6a73b34d70.py", line 7, in <module>
airflow      |     from airflow.contrib.operators.kubernetes_pod_operator import KubernetesPodOperator
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/kubernetes_pod_operator.py", line 24, in <module>
airflow      |     from airflow.contrib.kubernetes import kube_client, pod_generator, pod_launcher
airflow      |   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/kubernetes/pod_launcher.py", line 27, in <module>
airflow      |     from kubernetes import watch, client
airflow      | ModuleNotFoundError: No module named 'kubernetes' **

**Comment by willfleury** [comment]
@Christian-TD can you have a look at this when you get a moment? It was working which means something must have changed / a version of a docker image was overwritten?

**Comment by willfleury** [comment]
in the 2.7.1 release branch - it doesn't import this so i wonder what has happened https://github.com/ThinkBigAnalytics/AoaCoreService/blob/2.7.1/aoa-serving-engines/schedulers/airflow/dags/batch.py

**Comment by Christian-TD** [comment]
> in the 2.7.1 release branch - it doesn't import this so i wonder what has happened https://github.com/ThinkBigAnalytics/AoaCoreService/blob/2.7.1/aoa-serving-engines/schedulers/airflow/dags/batch.py

Ok, I'm on it

**Comment by Christian-TD** [comment]
Fixed https://github.com/ThinkBigAnalytics/AoaDockerComposeDemos/pull/27
