### ISSUE TITLE
Add external storage override yaml 

### ISSUE THREAD

**Issue by willfleury** [ThinkBigAnalytics/AoaDockerComposeDemos#34]
Add example override yaml to mount the relevant volumes in all containers so that the data is persisted externally. Add necessary comments in example 

This way we can upgrade or do docker compose cleanups without loosing data. Very important for real deployment.

@Christian-TD fyi

**Comment by Christian-TD** [comment]
fyi @willfleury now with https://github.com/ThinkBigAnalytics/AoaDockerComposeDemos/pull/53 local binds persistency is by default.

Closed by https://github.com/ThinkBigAnalytics/AoaDockerComposeDemos/pull/53
